version: 2

sources:
  - name: raw
    database: bluemar_dev_db
    schema: raw
    tables:
      - name: raw_gastos_operativos
      - name: raw_ingresos
      - name: raw_pago_planillos
      - name: raw_inventario_de_activos